<?php
/*****************************
	Vue: Plan de route
	Controleur: road-map/index
	Fichier: application\views\scripts\road-map
******************************/
$this->headTitle()->append("Les nouveautés");
$this->headMeta()->appendName('description', "Page présentant un planning prévisionnel des évolutions du jeu Soule Royale. Jouable entièrement dans un navigateur web, sans téléchargement. Soyez fin stratége pour mener votre équipe hauts sommets.");
?>
<h1>Le plan de route</h1>
<h2>Etape en cours</h2>
<h2>Prochaine Etape</h2>
<h2>Futurs Jalons</h2>
<h2>Evolutions Possibles</h2>
