<?php
/*****************************
	Vue: Site-Map
	Controleur: jeux/index
	Fichier: application\views\scripts\jeux\
******************************/
$this->headTitle()->append("Simulateur");
$this->headMeta()->appendName('description', "Un bon capitaine de soule royale se doit de maîtriser divers tactiques. Venez les affiner et les parfaires sur le simulateur de soule royale.");
?>
<h1>Simulateur</h1>
