<?php 
	$rootPath=$this->baseUrl();
	$currentPath=$rootPath."";
	$structurePath=$rootPath."structure/";
	$informationPath=$rootPath."informations/";
	$page=$this->escape($this->title);
	$title=$page;

	include_once $structurePath."header/header.php";	
	include_once $structurePath."content/content.php";	

	echo $this->layout()->content;
	
	include_once $rootPath."structure/footer/footer.php";
?>
	
