<?php
/*****************************
	VueScript: Contactez-Nous
	Controleur: contactez-nous/index
	Fichier: application\views\viewScript\ContactezNous\ContactezNous.phtml
******************************/
$form = $this->element;
?>
<form 	action="<?php echo $this->escape($form->getAction()); ?>"
		method="<?php echo $this->escape($form->getMethod()); ?>"
		class="formident" >
 
	<div>
		<span class="labelform"><label><?php $form->mail->getLabel()?> :</label></span>
		<span><?php echo $form->mail->renderViewHelper(); ?></span>
    </div>
    <div>
		<span class="labelform"><label><?php $form->mail->getLabel()?> :</label></span>
		<span><?php echo $form->mail->renderViewHelper(); ?></span>
    </div>
	<div>
		<span class="labelform"><label><?php $form->nom->getLabel()?> :</label></span>
		<span><?php echo $form->nom->renderViewHelper(); ?></span>
    </div>
	<div>
		<span class="labelform"><label><?php $form->equipe->getLabel()?> :</label></span>
		<span><?php echo $form->equipe->renderViewHelper(); ?></span>
    </div>
	<div>
		<span class="labelform"><label><?php $form->sujet->getLabel()?> :</label></span>
		<span><?php echo $form->sujet->renderViewHelper(); ?></span>
    </div>
	<div>
		<span class="labelform"><label><?php $form->message->getLabel()?> :</label></span>
		<span><?php echo $form->message->renderViewHelper(); ?></span>
    </div>
 
	<?php echo $form->submit->renderViewHelper(); ?>
 
</form>