<?php
/*****************************
	Vue: Site-Map
	Controleur: site-map/index
	Fichier: application\views\scripts\site-map
******************************/
$this->headTitle()->append("Contactez-nous");
$this->headMeta()->appendName('description', "Si vous rencontrez un problème ou que vous avez besoin d'informations sur la Soule Royale. C'est ici. Nous sommes à votre disposition.");
?>
<h1>Contactez-nous</h1>
<p>Les champs dont le libellé est précédé d'une "<span class='etoile'>*</span>" sont obligatoires. Merci de votre compréhension.</p>
<?php echo $this->form; $this->jQuery()->addJavascriptFile($this->baseUrl()."/js/".'helpers/validForms.js');?>