<?php
/*****************************
	VueScript: Contactez-Nous
	Controleur: contactez-nous/index
	Fichier: application\views\viewScript\ContactezNous\ContactezNous.phtml
******************************/
?>
<h1>Contactez-nous</h1>
<strong>Les champs en gras sont obligatoires.</strong>
<form 	action="<?php echo $this->escape($this->form->getAction()); ?>"
		method="<?php echo $this->escape($this->form->getMethod()); ?>"
		class="formident" >
 
	<table style="padding:2em;">		
		<tr>
			<td colspan="3"><?php echo $info["envoi"];?></td>
		</tr>
		<tr>
			<td>Anti-flood :</td>
			<td colspan="2">Merci de recopier le code contenu dans l'image ci-contre.</td>			
		</tr>
		<tr>
			<td><img src="<?php echo $rootPath?>libs/protection.php?name=livreor&amp;strlen=4" title="anti-flood" alt="anti-flood" /></td>
			<td style="vertical-align:text-top;"><input id="code" name="code" class="ui-widget" value=""/></td>
			<td style="vertical-align:text-top;" class="erreur"><?php echo $info["err_code"];?></td>
		</tr>
		<tr>
			<td><label id="lbl_email" class="obligatoire"><?php echo $this->form->mail->getLabel()?> :</label></td>
			<td><?php echo $this->form->mail->renderViewHelper(); ?></td>
			<td class="erreur"><?php echo $info["err_mail"];?></td>
		</tr>
		<tr>
			<td><label id="lbl_nom" class="obligatoire"><?php echo $this->form->nom->getLabel()?> :</label></td>
			<td><?php echo $this->form->nom->renderViewHelper(); ?></td>
			<td class="erreur"><?php echo $info["err_nom"];?></td>
		</tr>
		<tr>
			<td><label><?php echo $this->form->equipe->getLabel()?> :</label></td>
			<td><?php echo $this->form->equipe->renderViewHelper(); ?></td>
			<td class="erreur"><?php echo $info["err_equipe"];?></td>
		</tr>
		<tr>
			<td><label id="lbl_sujet" class="obligatoire"><?php echo $this->form->sujet->getLabel()?> :</label></td>
			<td><?php echo $this->form->sujet->renderViewHelper(); ?></td>
			<td class="erreur"><?php echo $info["err_sujet"];?></td>
		</tr>
		<tr>
			<td style="vertical-align:text-top;"><label id="lbl_Message"  class="obligatoire"><?php echo $this->form->message->getLabel()?> :</label></td>
			<td><?php echo $this->form->message->renderViewHelper(); ?></td>
			<td class="erreur" style="vertical-align:text-top;"><?php echo $info["err_message"];?></td>
		</tr>
		<tr>
			<td colspan="2" align="center"><?php echo $this->form->envoyer->renderViewHelper(); ?></td>
			<td colspan="2" align="center">&nbsp;</td>
		</tr>
	</table>
</form>