<?php
/*****************************
	Vue: PLes règles de la Soule Royale
	Controleur: information/regles
	Fichier: application\views\scripts\informations\regles
******************************/
$this->headTitle()->append("Les règles de la Soule Royale");
$this->headMeta()->appendName('description', "Règle du jeu en ligne gratuit multijoueur Soule Royale, Jouable entièrement dans un navigateur web, sans téléchargement. Soyez fin stratége pour mener votre équipe hauts sommets.");
$imageReglePath = $this->baseUrl()."/images/regles/";
?>

<h1>Les règles de la Soule Royale</h1>
<h2>1- Présentation</h2>
<h3>But du jeu</h3>
<p>Amener la <strong>soule</strong> dans la zone d'embut adverse. La première équipe qui place la <strong>soule</strong> dans la zone d'embut adverse remporte le match.</p>
<h3>Durée du match :</h3>
<p>Les matchs se jouent en 7 tours maximum.</p>
<h3>Actions possibles</h3>
<ul>
    <li>Frapper un adversaire.</li>
    <li>Avancer ou reculer.</li>
    <li>Pousser la soule.</li>
    <li>Ne rien faire.^^</li>
</ul>

<h4>Frapper un adversaire :</h4>
<p>Un joueur qui frappe, doit se trouver, au moment de l'action, sur la même ligne que le joueur visé pour pouvoir le toucher, sinon le coup ne porte pas. Chaque fois qu'un joueur est touché par un coup, il perd un point de vie. Chaque joueur commence le match avec 4 points de vie. Après 4 coups reçus, le joueur est ko et ne peut plus rien faire.</p>
<h4>Déplacer la soule :</h4>
<p>Un joueur pousse la <strong>Soule</strong> s'il se trouve dans la case précédent la soule et qu'il avance.</p>
<img src="<?php echo $imageReglePath?>Pousse_soule.gif" alt="joueur poussant la soule" title="joueur poussant la soule" /><br />


<p>Les différentes phases de jeu sont illustrées ci-dessous.</p>
<h3>Légende :</h3>
<ul>
    <li>Un + signifie que le joueur avance.</li>
    <li>Un - signifie que le joueur recule.</li>
    <li>Un zéro, qu'il ne fait aucune action.</li>
    <li>Un chiffre près d'un joueur, signifie qu'il tente de frapper l'adversaire portant ce numéro.</li>
    <li>Chaque point noir, représente une blessure, la perte d'un point de vie. A 4 points de vie perdu c'est le KO.</li>
    <li>Un X, signifie que le joueur est KO et ne peut donc entreprendre aucune action.</li>
</ul>
<h2>2- Le déroulement d'un match :</h2><p>Les deux équipes fournissent les positions initiales de leurs joueurs, également appelée les "initiales". Puis à chaque tour, elles communiquent les actions de chacun des joueurs qui la compose.</p>
<p>Les joueurs agissent, alternativement, dans l'ordre des numéos. Le joueur <span class="Equipe1">n°1 de l'équipe 1</span> agit en premier, puis c'est au tour du joueur <span class="Equipe2">n°1 de l'équipe 2</span> puis après le joueur <span class="Equipe1">n°2 de l'équipe 1</span> et ainsi de suite... Lors du tour suivant, c'est le joueur <span class="Equipe2">n°1 de l'équipe 2</span> qui commencera.</p>

<h3>Exemple :</h3>
<p>Les initiales<br />
	<span class="Equipe1">Equipe 1 : 2 1 1 1 1 2 1 1 1 1 2</span><br /> <!-- Rouge -->
    <span class="Equipe2">Equipe 2 : 1 1 1 1 2 1 1 2 2 2 1</span> <!-- Bleu -->
</p>
 <p>
	Puis, lors de la phase suivante, les actions des 11 joueurs de chaque équipe :<br />
    <span class="Equipe1">Equipe 1 : 0 - 0 0 0 + + + + + -</span><br />
    <span class="Equipe2">Equipe 2 : + + + + 0 + + 0 + + +</span><br />
</p>
<p>
  Le moteur du jeu analyse les actions et les applique sur le terrain :<br />
  <img src="<?php echo $imageReglePath?>Phase1.gif" title="soule royale: exemple de tour 1"  alt="soule royale: exemple de tour 1" /><br />
  Le premier tour est terminé.
</p>
<p>
    Les actions des 11 joueurs de chaque équipe pour le tour suivant :<br />
    <span class="Equipe1">Equipe 1 : 0 + 1 + 1 + + 11 11 + +</span><br />
	<span class="Equipe2">Equipe 2 : + 7 7 + + 7 7 + + + 8</span>
</p>
<p>
	Le résultat des actions :<br />
    <img src="<?php echo $imageReglePath?>Phase2.gif" title="soule royale: exemple de tour 2"  alt="soule royale: exemple de tour 2"  /><br />
	Le second tour est terminé
</p>
<p>
    Les actions des 11 joueurs de chaque équipe pour le tour suivant :<br />
    <span class="Equipe1">Equipe 1 : + + 1 + 1 11 X 11 11 + 0</span><br />
	<span class="Equipe2">Equipe 2 : - 9 9 - - 9 9 8 8 8 8</span>
</p>
<p>
    Le résultat des actions :<br />
    <img src="<?php echo $imageReglePath?>Phase3.gif" title="soule royale: exemple de tour 3"  alt="soule royale: exemple de tour 3" /><br />
 </p>
 <h4>La soule atteint la ligne d'embut. La victoire revient à l'<span class="Equipe1">équipe 1</span> au troisième tour.</h4>
 Nous vous invitons à faire vos premier pas sur le simulateur.
